### ISSUE TITLE
Prevent image upload when not signed in.

### ISSUE THREAD

**Issue by ashefor** [Mayowa-Ojo/Newbie-backend-#3]
Right now a logged out or anonymous user can upload images

**Comment by Mayowa-Ojo** [comment]
Implemented authorization on image uploads. Be sure to pull for the newest updates and give feedback so I can close this issue.

Gracias 👌

**Comment by ashefor** [comment]
Okay

**Comment by Mayowa-Ojo** [comment]
No feedback on this

**Comment by ashefor** [comment]
Checked and it's authenticated. Works fine.
